// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mission8.Data;

#nullable disable

namespace mission8.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("mission8.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Home"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "School"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Work"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Church"
                        });
                });

            modelBuilder.Entity("mission8.Models.ToDoTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quadrant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            CategoryId = 1,
                            Completed = false,
                            DueDate = new DateOnly(2026, 3, 1),
                            Quadrant = 1,
                            Task = "Pay rent"
                        },
                        new
                        {
                            TaskId = 2,
                            CategoryId = 2,
                            Completed = false,
                            DueDate = new DateOnly(2026, 3, 5),
                            Quadrant = 1,
                            Task = "Study for midterm"
                        },
                        new
                        {
                            TaskId = 3,
                            CategoryId = 1,
                            Completed = false,
                            Quadrant = 2,
                            Task = "Build exercise routine"
                        },
                        new
                        {
                            TaskId = 4,
                            CategoryId = 2,
                            Completed = false,
                            DueDate = new DateOnly(2026, 3, 10),
                            Quadrant = 2,
                            Task = "Complete IS413 group project"
                        },
                        new
                        {
                            TaskId = 5,
                            CategoryId = 3,
                            Completed = false,
                            Quadrant = 3,
                            Task = "Reply to work emails"
                        },
                        new
                        {
                            TaskId = 6,
                            CategoryId = 3,
                            Completed = false,
                            Quadrant = 3,
                            Task = "Attend optional department meeting"
                        },
                        new
                        {
                            TaskId = 7,
                            CategoryId = 1,
                            Completed = false,
                            Quadrant = 4,
                            Task = "Browse social media"
                        },
                        new
                        {
                            TaskId = 8,
                            CategoryId = 3,
                            Completed = false,
                            Quadrant = 4,
                            Task = "Organize old files"
                        });
                });

            modelBuilder.Entity("mission8.Models.ToDoTask", b =>
                {
                    b.HasOne("mission8.Models.Category", "Category")
                        .WithMany("Tasks")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("mission8.Models.Category", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
